name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # or your deployment branch

permissions:
  id-token: write  # Required for OIDC token
  contents: read   # To checkout repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REPO_NAME }} .
          docker tag ${{ secrets.REPO_TAG }}
          
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.REPO_PUSH }}
